title: Adriano Wanderlingh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  As a data analyst with a PhD in biostatistics, I excel at uncovering valuable insights from a large variety of data sources. I leverage R, Python, SQL, and Tableau to deliver data-driven solutions tailored to my clients' needs.
  <br><br>
  ğŸ› ï¸ Proficient in data cleaning, statistical modeling, machine learning, and network analysis.<br>
  ğŸ’¡ Skilled in handling large, complex datasets with a creative problem-solving approach.<br>
  ğŸ“ˆ Adept at transforming raw data into actionable intelligence and insightful visualizations.<br>
  ğŸ’¬ Effective communicator, able to translate technical findings into clear, impactful insights.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/a-wanderlingh/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
